context:
  version: "1.2.2"
  build_number: 1000

package:
  name: zenoh-python
  version: ${{ version }}

source:
  git: https://github.com/eclipse-zenoh/zenoh-python.git
  tag: ${{ version }}

build:
  number: ${{ build_number }}
  string: py${{ python | replace(".", "") }}h${{ hash }}_${{ build_number }}

requirements:
  build:
    - ${{ compiler('rust') }}
  host:
    - python
    - maturin
    - fixtures
  run:
    - python

tests:
  - python:
      imports:
        - zenoh

about:
  homepage: https://zenoh.io/
  summary: Zero Overhead Network Protocol.
  description: |
    Zenoh is a pub/sub/query protocol unifying data in motion,
    data at rest and computations. It elegantly blends traditional pub/sub
    with geo distributed storage, queries and computations, while retaining
    a level of time and space efficiency that is well beyond any of the mainstream stacks
